package cz.stasimek.fakturaceeasypeasy.enumeration

enum class Country(public val nameCs: String) {
    CZE("Česko"),
    SVK("Slovensko"),
    AFG("Afghánistán"),
    ALA("Alandy"),
    ALB("Albánie"),
    DZA("Alžírsko"),
    ASM("Americká Samoa"),
    VIR("Americké Panenské ostrovy"),
    AND("Andorra"),
    AGO("Angola"),
    AIA("Anguilla"),
    ATA("Antarktida"),
    ATG("Antigua a Barbuda"),
    ARG("Argentina"),
    ARM("Arménie"),
    ABW("Aruba"),
    AUS("Austrálie"),
    AZE("Ázerbájdžán"),
    BHS("Bahamy"),
    BHR("Bahrajn"),
    BGD("Bangladéš"),
    BRB("Barbados"),
    BEL("Belgie"),
    BLZ("Belize"),
    BLR("Bělorusko"),
    BEN("Benin"),
    BMU("Bermudy"),
    BTN("Bhútán"),
    BOL("Bolívie"),
    BES("Bonaire, Svatý Eustach a Saba"),
    BIH("Bosna a Hercegovina"),
    BWA("Botswana"),
    BVT("Bouvetův ostrov"),
    BRA("Brazílie"),
    IOT("Britské indickooceánské území"),
    VGB("Britské Panenské ostrovy"),
    BRN("Brunej"),
    BGR("Bulharsko"),
    BFA("Burkina Faso"),
    BDI("Burundi"),
    COK("Cookovy ostrovy"),
    CUW("Curaçao"),
    TCD("Čad"),
    MNE("Černá Hora"),
    CHN("Čína"),
    DNK("Dánsko"),
    DMA("Dominika"),
    DOM("Dominikánská republika"),
    DJI("Džibutsko"),
    EGY("Egypt"),
    ECU("Ekvádor"),
    ERI("Eritrea"),
    EST("Estonsko"),
    ETH("Etiopie"),
    FRO("Faerské ostrovy"),
    FLK("Falklandy (Malvíny)"),
    FJI("Fidži"),
    PHL("Filipíny"),
    FIN("Finsko"),
    FRA("Francie"),
    GUF("Francouzská Guyana"),
    ATF("Francouzská jižní a antarktická území"),
    PYF("Francouzská Polynésie"),
    GAB("Gabon"),
    GMB("Gambie"),
    GHA("Ghana"),
    GIB("Gibraltar"),
    GRD("Grenada"),
    GRL("Grónsko"),
    GEO("Gruzie"),
    GLP("Guadeloupe"),
    GUM("Guam"),
    GTM("Guatemala"),
    GIN("Guinea"),
    GNB("Guinea-Bissau"),
    GGY("Guernsey"),
    GUY("Guyana"),
    HTI("Haiti"),
    HMD("Heardův ostrov a McDonaldovy ostrovy"),
    HND("Honduras"),
    HKG("Hongkong"),
    CHL("Chile"),
    HRV("Chorvatsko"),
    IND("Indie"),
    IDN("Indonésie"),
    IRQ("Irák"),
    IRN("Írán"),
    IRL("Irsko"),
    ISL("Island"),
    ITA("Itálie"),
    ISR("Izrael"),
    JAM("Jamajka"),
    JPN("Japonsko"),
    YEM("Jemen"),
    JEY("Jersey"),
    ZAF("Jihoafrická republika"),
    SGS("Jižní Georgie a Jižní Sandwichovy ostrovy"),
    KOR("Jižní Korea"),
    SSD("Jižní Súdán"),
    JOR("Jordánsko"),
    CYM("Kajmanské ostrovy"),
    KHM("Kambodža"),
    CMR("Kamerun"),
    CAN("Kanada"),
    CPV("Kapverdy"),
    QAT("Katar"),
    KAZ("Kazachstán"),
    KEN("Keňa"),
    KIR("Kiribati"),
    CCK("Kokosové ostrovy"),
    COL("Kolumbie"),
    COM("Komory"),
    COG("Kongo"),
    COD("Konžská demokratická republika"),
    CRI("Kostarika"),
    CUB("Kuba"),
    KWT("Kuvajt"),
    CYP("Kypr"),
    KGZ("Kyrgyzstán"),
    LAO("Laos"),
    LSO("Lesotho"),
    LBN("Libanon"),
    LBR("Libérie"),
    LBY("Libye"),
    LIE("Lichtenštejnsko"),
    LTU("Litva"),
    LVA("Lotyšsko"),
    LUX("Lucembursko"),
    MAC("Macao"),
    MDG("Madagaskar"),
    HUN("Maďarsko"),
    MYS("Malajsie"),
    MWI("Malawi"),
    MDV("Maledivy"),
    MLI("Mali"),
    MLT("Malta"),
    IMN("Ostrov Man"),
    MAR("Maroko"),
    MHL("Marshallovy ostrovy"),
    MTQ("Martinik"),
    MUS("Mauricius"),
    MRT("Mauritánie"),
    MYT("Mayotte"),
    UMI("Menší odlehlé ostrovy USA"),
    MEX("Mexiko"),
    FSM("Mikronésie"),
    MDA("Moldavsko"),
    MCO("Monako"),
    MNG("Mongolsko"),
    MSR("Montserrat"),
    MOZ("Mosambik"),
    MMR("Myanmar"),
    NAM("Namibie"),
    NRU("Nauru"),
    DEU("Německo"),
    NPL("Nepál"),
    NER("Niger"),
    NGA("Nigérie"),
    NIC("Nikaragua"),
    NIU("Niue"),
    NLD("Nizozemsko"),
    NFK("Norfolk"),
    NOR("Norsko"),
    NCL("Nová Kaledonie"),
    NZL("Nový Zéland"),
    OMN("Omán"),
    PAK("Pákistán"),
    PLW("Palau"),
    PSE("Palestinská autonomie"),
    PAN("Panama"),
    PNG("Papua Nová Guinea"),
    PRY("Paraguay"),
    PER("Peru"),
    PCN("Pitcairnovy ostrovy"),
    CIV("Pobřeží slonoviny"),
    POL("Polsko"),
    PRI("Portoriko"),
    PRT("Portugalsko"),
    AUT("Rakousko"),
    REU("Réunion"),
    GNQ("Rovníková Guinea"),
    ROU("Rumunsko"),
    RUS("Rusko"),
    RWA("Rwanda"),
    GRC("Řecko"),
    SPM("Saint Pierre a Miquelon"),
    SLV("Salvador"),
    WSM("Samoa"),
    SMR("San Marino"),
    SAU("Saúdská Arábie"),
    SEN("Senegal"),
    PRK("Severní Korea"),
    MKD("Severní Makedonie"),
    MNP("Severní Mariany"),
    SYC("Seychely"),
    SLE("Sierra Leone"),
    SGP("Singapur"),
    SVN("Slovinsko"),
    SOM("Somálsko"),
    ARE("Spojené arabské emiráty"),
    GBR("Spojené království Velké Británie a Severního Irska"),
    USA("Spojené státy americké"),
    SRB("Srbsko"),
    LKA("Srí Lanka"),
    CAF("Středoafrická republika"),
    SDN("Súdán"),
    SUR("Surinam"),
    SHN("Svatá Helena, Ascension a Tristan da Cunha"),
    LCA("Svatá Lucie"),
    BLM("Svatý Bartoloměj"),
    KNA("Svatý Kryštof a Nevis"),
    MAF("Svatý Martin (francouzská část)"),
    SXM("Svatý Martin (nizozemská část)"),
    STP("Svatý Tomáš a Princův ostrov"),
    VCT("Svatý Vincenc a Grenadiny"),
    SWZ("Svazijsko"),
    SYR("Sýrie"),
    SLB("Šalomounovy ostrovy"),
    ESP("Španělsko"),
    SJM("Špicberky a Jan Mayen"),
    SWE("Švédsko"),
    CHE("Švýcarsko"),
    TJK("Tádžikistán"),
    TZA("Tanzanie"),
    THA("Thajsko"),
    TWN("Tchaj-wan"),
    TGO("Togo"),
    TKL("Tokelau"),
    TON("Tonga"),
    TTO("Trinidad a Tobago"),
    TUN("Tunisko"),
    TUR("Turecko"),
    TKM("Turkmenistán"),
    TCA("Turks a Caicos"),
    TUV("Tuvalu"),
    UGA("Uganda"),
    UKR("Ukrajina"),
    URY("Uruguay"),
    UZB("Uzbekistán"),
    CXR("Vánoční ostrov"),
    VUT("Vanuatu"),
    VAT("Vatikán"),
    VEN("Venezuela"),
    VNM("Vietnam"),
    TLS("Východní Timor"),
    WLF("Wallis a Futuna"),
    ZMB("Zambie"),
    ESH("Západní Sahara"),
    ZWE("Zimbabwe");

    companion object {
        fun valuesMap(): Map<String, String> {
            return values()
                .map { it.name to it.nameCs }
                .toMap(LinkedHashMap())
        }
    }
}