create table subject (
	id char(16) for bit data not null,
	"user_id" char(16) for bit data not null,
	type varchar(20) not null,
	legal_form varchar(20) not null,
	company_name varchar(255) not null,
	street varchar(100) not null,
	city varchar(100) not null,
	zip varchar(10) not null,
	country varchar(3) not null,
	company_number varchar(20),
	vat_number varchar(20),
	default_due_period integer,
	default_currency varchar(3),
	created_at timestamp not null,
	updated_at timestamp not null,
	deleted boolean,
	primary key (id),
	constraint FK_subject_user_id foreign key ("user_id") references "user"
);
